[[query]]
  statement = "SELECT count(value) from cpu"
  database = "stress"
  runs = 3
  point_count = 10000000 # optional parameter for the number of points that were queried

[[query]]
  statement = "SELECT * FROM cpu WHERE host='server-1'"
  database = "stress"
  runs = 10
  point_count = 100 # optional parameter for the number of points that were queried

[[query]]
  statement = "SELECT * FROM cpu WHERE host='server-5'"
  database = "stress"
  runs = 10
  point_count = 100 # optional parameter for the number of points that were queried

[[query]]
  statement = "SELECT * FROM cpu WHERE host='server-10'"
  database = "stress"
  runs = 10
  point_count = 100 # optional parameter for the number of points that were queried

[[query]]
  statement = "SELECT * FROM cpu WHERE host='server-50'"
  database = "stress"
  runs = 10
  point_count = 100 # optional parameter for the number of points that were queried

[[query]]
  statement = "SELECT * FROM cpu WHERE host='server-100'"
  database = "stress"
  runs = 10
  point_count = 100 # optional parameter for the number of points that were queried

[[query]]
  statement = "SELECT * FROM cpu WHERE host='server-500'"
  database = "stress"
  runs = 10
  point_count = 100 # optional parameter for the number of points that were queried

[[query]]
  statement = "SELECT * FROM cpu WHERE host='server-1000'"
  database = "stress"
  runs = 10
  point_count = 100 # optional parameter for the number of points that were queried

[[query]]
  statement = "SELECT * FROM cpu WHERE host='server-5000'"
  database = "stress"
  runs = 10
  point_count = 100 # optional parameter for the number of points that were queried

[[query]]
  statement = "SELECT * FROM cpu WHERE host='server-10000'"
  database = "stress"
  runs = 10
  point_count = 100 # optional parameter for the number of points that were queried

[[query]]
  statement = "SELECT * FROM cpu WHERE host='server-50000'"
  database = "stress"
  runs = 10
  point_count = 100 # optional parameter for the number of points that were queried

[[query]]
  statement = "SELECT * FROM cpu WHERE host='server-99999'"
  database = "stress"
  runs = 10
  point_count = 100 # optional parameter for the number of points that were queried
